.TH fiflo 1 "General Commands Manual"
.SH NAME
fiflo - simple terminal-based text editor.
.SH SYNOPSIS
fiflo [option]
.SH DESCRIPTION
Currently under WIP.
Whole project is licensed under the MIT License.
.SH OPTIONS
.TP
.B <NULL>
Create and open the default file - "noname.asdf".
.TP
.B <file>
Open the textfile named "file". Passing absolute/relative is possible.
.TP
.B -h, --help
Show program help.
.SH SEE ALSO
https://gitlab.com/mattmaniak/fiflo
.SH BUGS
Probably some.
.SH AUTHOR
mattmaniak