.TH fiflo 1 "General Commands Manual"
.SH NAME
.TP
fiflo
.SH SYNOPSIS
fiflo [option]
.SH DESCRIPTION
User-friendly ASCII terminal-based text editor.
.SH OPTIONS
.TP
.B <no_option>
Don't set a filename. Only a current path will be set.
.TP
.B <name>
Specify a base/filename.
.TP
.B -h, --help
Show a program help.
.TP
.B -v, --version
Display information about a version You use.
.SH BINDINGS
'^' (carret) means that the neighbour keys are should be pressed at the same \
moment. The program supports partial Common User Access.
.TP
.B CTRL^D
Delete a current line.
.TP
.B CTRL^O
Save as - edit and save with a different name (confirm by the ENTER).
.TP
.B CTRL^Q
Exit the program.
.TP
.B CTRL^S
Save a file with a filename specified in the upper bar.
.TP
.B ARROWS
Move the cursor one char/line in a specified direction.
.SH SEE ALSO
https://gitlab.com/mattmaniak/fiflo.git
.SH BUGS
Maybe.
.SH AUTHOR
mattmaniak
