.TH fiflo 1 "General Commands Manual"

.SH NAME
fiflo - simple terminal-based text editor.

.SH SYNOPSIS
fiflo [option]

.SH DESCRIPTION
Simple, fast and probably no-user-friendly text editor for *nix guys.
The whole project licensed under the MIT License.

.SH OPTIONS
.TP
.B -h, --help
Show program help.

.SH SEE ALSO
random-git-remote-repo.com/mattmaniak/fiflo

.SH BUGS
Probably some.

.SH AUTHOR
mattmaniak
