.TH fiflorc 5 "File Formats Manual"
.SH NAME
fiflo configuration file
.SH SYNOPSIS
.TP
[selector] = [value]
Everything in a single line. Next one in a next line. Single neighbour spaces
around the equality sign are essential.
.SH DESCRIPTION
File that allows to change the default configuration of the fiflo which is
built-in in the editor. It ignores lines that starts with a whitespace, with
the '#' or just empty ones. If You use a one of selectors multiple times.
.SH SELECTORS
An order doesn't matter.
.TP
.B color_actual_file
Visible if the lower bar is toggled.
.TP
.B color_line_number
Set line numbers color excluding a current one.
.TP
.B color_line_number_actual
Set the current line number color.
.TP
.B color_text
Color of a typed text.
.TP
.B color_ui
Upper and lower bar text color.
.TP
.B color_warning
When sometimes goes wrong a part of the UI is highlighted with this color.
Actually it is only the punch card indicator.
.TP
.B color_whitespace
Tabs and spaces highlighting.
.TP
.B tab_size
Equality of spaces that the tab key produces.
.SH VALUES
.TP
.B red, green, yellow, blue, magenta, cyan, white, bright_black, bright_red, \
bright_green, bright_yellow, bright_blue, bright_magenta, bright_cyan, \
bright_white
Available colors. Every one of them is a foreground color. There is no
possibility to set the background. Can be used only with selectors that starts
with "color".
.TP
.B <2; 8>
Available tab width.
.SH WRONG SYNTAX HANDLING
If the selector or value is wrong or if there is no trailing newline at the end
of the file, the default value will be applied. Else if the selector and value
are wrong, default editor's configuration will be applied.
.SH FILES
.TP
.B /etc/fiflorc
The only and global confiuguration. If doesn't exist, the default config will
be applied.
.SH SEE ALSO
fiflo(1)
.SH AUTHOR
mattmaniak
